version: '3.8'

services:
  mysql-batch:
    image: mysql:8

    container_name: mysql-for-batch

    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: batch_practice
      TZ: Asia/Seoul

    ports:
      - "3306:3306"

    volumes:
      - mysql-batch-data:/var/lib/mysql

volumes:
  mysql-batch-data: